
import ServicePageLayout from '../../components/services/ServicePageLayout';

const PortfolioRationalizationBusinessExits = () => {
  const data = {
    metaTitle: "Portfolio Rationalization & Business Exits | Northrop India",
    metaDescription: "Every business in your portfolio earned its place. Most are no longer paying rent.",
    breadcrumbs: [
      { name: "Home", link: "/" },
      { name: "Management Consulting", link: null },
      { name: "Portfolio Rationalization", link: null }
    ],
    bannerTitle: <>Every business in your portfolio earned its place.<br /> <span className="text-[#C4973B]">Most are no longer paying rent.</span></>,
    bannerDescription: "Portfolios are not built — they accrete. Acquisitions, founder pet projects, and legacy operations stay because exiting is uncomfortable. Each underperforming unit drains management attention, capital, and equity multiple — quietly, continuously.",
    primaryBtnText: "Get Portfolio Advisory",
    secondaryBtnText: "Request a Carve-Out Review",
    svcNum: "MC — 05 /",
    svcTag: "Portfolio Rationalization & Business Exits",
    svcH2: <>INDUSTRY-SPECIFIC PORTFOLIO FAILURES <br /><em className="italic text-[#C4973B] not-italic">— AND THEIR COST</em></>,
    hookText: "Each underperforming unit drains management attention, capital, and equity multiple — quietly, continuously. Here is what portfolio failures look like across industries:",
    painLabel: "What portfolio failures look like — by industry",
    painList: [
      { label: "Diversified Groups", text: "40–60% of group EBITDA generated by 20% of business units. Sub-scale units consume management bandwidth disproportionate to their economic contribution. Sum-of-parts gap to traded value is 25–35%." },
      { label: "Manufacturing Conglomerates", text: "Legacy plants kept open on emotional and political grounds. Cost-of-capital-adjusted return is sharply negative; carbon and ESG exposure compounds." },
      { label: "Listed Holdcos", text: "Holdco discount widens because the market cannot price the portfolio. No clear exit pathway communicated to investors." },
      { label: "PE-Backed Platforms", text: "Bolt-on acquisitions integrated only at the GL level. Product, channel, and geographic redundancy never resolved — exit multiple compresses." }
    ],
    delGrid: [
      { title: "Portfolio Economic-Profit Map", desc: "Business-unit-level economic profit, capital intensity, and strategic fit assessment — without the politics." },
      { title: "Hold / Fix / Exit Framework", desc: "Defensible classification of each unit on capital efficiency, strategic relevance, and exit feasibility." },
      { title: "Carve-Out Architecture", desc: "Operational, legal, tax, and financial separation design — exit-ready entities, not just exit-ready spreadsheets." },
      { title: "Exit Execution Strategy", desc: "Buyer mapping, value narrative, deal structuring, and process management — through to close." }
    ],
    outcomes: [
      "Portfolio Discipline Restored",
      "SOTP Discount Closed",
      "Exit-Ready Entities",
      "Capital Released",
      "Management Bandwidth Recovered",
      "Conglomerate Premium"
    ],
    whoGrid: [
      { title: "Diversified Groups", desc: "Where the holding company trades at a discount the underlying businesses do not deserve." },
      { title: "PE-Backed Platforms", desc: "Preparing for a strategic or secondary exit and needing portfolio coherence." },
      { title: "Family Businesses", desc: "Where legacy units must be separated from growth platforms before succession or capital event." },
      { title: "CEOs Entering a New Mandate", desc: "To reset the portfolio thesis before the next strategic cycle begins." }
    ],
    ctaPrimaryText: "Get Portfolio Advisory",
    ctaSecondaryText: "Request a Carve-Out Review",
    trustNote: "Northrop has advised on portfolio rationalisation and business carve-outs across diversified groups, manufacturing conglomerates, and PE-backed platforms in India.",
    closingTitle: "Holding a business is a decision. Pretending it isn't is a more expensive one.",
    // closingDescription: "Every engagement starts with a confidential conversation. No obligation — just clarity on your specific exposure and how Northrop can help."
  };

  return <ServicePageLayout {...data} />;
};

export default PortfolioRationalizationBusinessExits;
