import React, { useEffect } from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';

const EsgAsAlpha = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="bg-[#f8f9fa] text-[#191c1d] font-sans overflow-x-hidden">
      <Helmet>
        <title>ESG as Alpha | Northrop India Strategic Advisory</title>
      </Helmet>

      {/* Hero Section */}
      <header className="relative w-full h-[819px] flex flex-col items-center justify-center text-center overflow-hidden">
        <div 
          className="absolute inset-0 z-0 bg-cover bg-center" 
          style={{ backgroundImage: "url('/insightpage/esgalpha1.png')" }}
        ></div>
        <div 
          className="absolute inset-0 z-10" 
          style={{ background: "linear-gradient(to bottom, rgba(0, 31, 63, 0.4), rgba(0, 31, 63, 0.8))" }}
        ></div>
        <div className="relative z-20 px-[20px] md:px-[64px] max-w-4xl mx-auto flex flex-col items-center">
          <h1 className="font-serif text-[32px] md:text-[48px] leading-[40px] md:leading-[56px] font-bold tracking-[-0.02em] text-white mb-6 uppercase">
            ESG AS ALPHA: THE DECOUPLING OF ESG SENTIMENT FROM MATERIAL FINANCIAL PERFORMANCE IN 2026
          </h1>
          <div className="w-24 h-1 bg-[#7c5800] mb-8"></div>
          <p className="text-[16px] md:text-[18px] leading-[24px] md:leading-[28px] text-white/80 max-w-2xl font-normal">
            A forensic analysis of the emerging divergence between public perception and core financial resilience in the Indian M&A landscape.
          </p>
        </div>
      </header>

      <main 
        className="w-full max-w-[1200px] mx-auto px-[20px] md:px-[64px] py-20"
        style={{ backgroundImage: "radial-gradient(#c5c6cd 0.5px, transparent 0.5px)", backgroundSize: "24px 24px" }}
      >
        {/* Section 01: The Materiality Gap */}
        <section className="mb-32 grid grid-cols-1 md:grid-cols-12 gap-[24px] items-start">
          <div className="md:col-span-4 sticky top-28">
            <span className="text-[#7c5800] text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase block mb-4">SECTION 01</span>
            <h2 className="font-serif text-[28px] md:text-[32px] leading-[36px] md:leading-[40px] font-semibold text-[#001F3F] mb-4">THE MATERIALITY Gap</h2>
            <p className="text-[#4A5568] text-[16px] leading-[24px] border-l-2 border-[#001F3F] pl-6 italic">
              "2026 marks the year where sentiment alone no longer secures capital. The market has shifted toward verifiable, forensic-grade materiality."
            </p>
          </div>
          <div className="md:col-span-8">
            <p className="text-[16px] md:text-[18px] leading-[28px] text-[#191c1d] mb-8 font-normal">
              In the previous cycle, Environmental, Social, and Governance (ESG) factors were often treated as reputational buffers—qualitative measures used to appease social mandates. However, our 2026 analysis reveals a sharp <span className="font-bold">decoupling</span>. Financial performance is no longer tethered to general "ESG Sentiment." Instead, Alpha is being generated by a narrow set of "Materiality Anchors."
            </p>
            <p className="text-[16px] leading-[24px] text-[#45474c] mb-6">
              Investors are now discounting "green" narratives that lack forensic evidentiary support. The transition from BRSR Core compliance to forensic-grade ESG auditing has created a value wedge: firms that treat ESG as a financial mandate outperform peers by 14.2% in post-close valuation stability.
            </p>
            <div className="bg-[#f3f4f5] p-8 border border-[#c5c6cd]">
              <h4 className="text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase text-[#001F3F] mb-4">FORENSIC FINDING</h4>
              <p className="text-[16px] leading-[24px]">92% of institutional investors now deploy secondary forensic teams specifically to audit ESG reporting lines prior to deal signing, up from 34% in 2024.</p>
            </div>
          </div>
        </section>

        {/* Section 02: Forensic Alpha Metrics */}
        <section className="mb-32">
          <div className="text-center mb-16">
            <span className="text-[#7c5800] text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase block mb-4">SECTION 02</span>
            <h2 className="font-serif text-[28px] md:text-[32px] leading-[36px] md:leading-[40px] font-semibold text-[#001F3F]">FORENSIC ALPHA METRICS</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-[24px]">
            <div className="bg-white border border-[#c5c6cd] p-10 flex flex-col items-center text-center relative overflow-hidden group">
              <div className="absolute top-0 left-0 w-full h-1 bg-[#001F3F]"></div>
              <span className="font-serif text-[40px] md:text-[48px] leading-[48px] md:leading-[56px] font-bold tracking-[-0.02em] text-[#001F3F] group-hover:text-[#7c5800] transition-colors">12-15%</span>
              <span className="text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase text-[#4A5568] mt-2 mb-4">VALUATION PREMIUM</span>
              <p className="text-[14px] leading-[20px]">Observed premium for assets with mature, forensic-grade carbon mitigation structures in Tier-1 industrial sectors.</p>
            </div>
            <div className="bg-white border border-[#c5c6cd] p-10 flex flex-col items-center text-center relative overflow-hidden group">
              <div className="absolute top-0 left-0 w-full h-1 bg-[#001F3F]"></div>
              <span className="font-serif text-[40px] md:text-[48px] leading-[48px] md:leading-[56px] font-bold tracking-[-0.02em] text-[#001F3F] group-hover:text-[#7c5800] transition-colors">82%</span>
              <span className="text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase text-[#4A5568] mt-2 mb-4">INVESTOR SCRUTINY</span>
              <p className="text-[14px] leading-[20px]">Proportion of global mandates requiring audit-ready Scope 3 transparency data before initial LOI submission.</p>
            </div>
            <div className="bg-white border border-[#c5c6cd] p-10 flex flex-col items-center text-center relative overflow-hidden group">
              <div className="absolute top-0 left-0 w-full h-1 bg-[#001F3F]"></div>
              <span className="font-serif text-[40px] md:text-[48px] leading-[48px] md:leading-[56px] font-bold tracking-[-0.02em] text-[#001F3F] group-hover:text-[#7c5800] transition-colors">94%</span>
              <span className="text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase text-[#4A5568] mt-2 mb-4">ASSURANCE READINESS</span>
              <p className="text-[14px] leading-[20px]">Target threshold for BRSR Core indicators required to avoid regulatory enforcement actions in the 2026 fiscal year.</p>
            </div>
          </div>
        </section>

        {/* Section 03: The Four Pillars */}
        <section className="mb-32">
          <div className="flex flex-col md:flex-row gap-12 items-center mb-16">
            <div className="w-full md:w-1/2">
              <span className="text-[#7c5800] text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase block mb-4">SECTION 03</span>
              <h2 className="font-serif text-[28px] md:text-[32px] leading-[36px] md:leading-[40px] font-semibold text-[#001F3F] mb-6">THE FOUR PILLARS OF ESG ALPHA</h2>
              <p className="text-[16px] leading-[24px] text-[#45474c]">Strategic value is no longer a monolith. It is built upon four distinctive pillars of forensic rigor.</p>
            </div>
            <div className="w-full md:w-1/2 h-64 bg-[#001F3F] flex items-center justify-center">
              <div className="w-full h-full relative">
                <div 
                  className="w-full h-full bg-cover bg-center opacity-60" 
                  style={{ backgroundImage: "url('https://lh3.googleusercontent.com/aida-public/AB6AXuC8eOAxOvZk65nF06yH3pnE8Q3N90kvIAHrBRbYO_OpKWeY7FI16-d-8qgdUqKKb1Bze4VMJ74ZIbwnmaT2XsCeBEWii-YEiKcnpDsq2WytBf7Uc9pxgv0zAoRnOoqe_jc00BVx4H2b4eZ89zv8arxB1gw8QHEXRzy8CCnQJu6YbEQGFqbHwLc__pD3oJ_zy6XJRjgvOpI_6D_Lf_DlQmPsbZRxctyvmM4BM5G6CwRcTLv1izRirQ9_oX3U_udFtM71PNVsCZEblCJo')" }}
                ></div>
                <div className="absolute inset-0 flex items-center justify-center">
                  <span className="material-symbols-outlined text-white text-6xl">architecture</span>
                </div>
              </div>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-[24px]">
            <div className="border-t-4 border-[#001F3F] pt-6">
              <h3 className="text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase text-[#001F3F] mb-3">01. SPECIFIC MATERIALITY</h3>
              <p className="text-[14px] leading-[20px]">Identifying sector-specific triggers that directly impact EBITDA, moving beyond generic ESG disclosures.</p>
            </div>
            <div className="border-t-4 border-[#001F3F] pt-6">
              <h3 className="text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase text-[#001F3F] mb-3">02. VERIFIABLE DATA</h3>
              <p className="text-[14px] leading-[20px]">Implementing blockchain-backed reporting streams that allow for instantaneous, real-time forensic auditing.</p>
            </div>
            <div className="border-t-4 border-[#001F3F] pt-6">
              <h3 className="text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase text-[#001F3F] mb-3">03. DOUBLE MATERIALITY</h3>
              <p className="text-[14px] leading-[20px]">Assessing how the entity impacts the world AND how environmental shifts impact the balance sheet.</p>
            </div>
            <div className="border-t-4 border-[#001F3F] pt-6">
              <h3 className="text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase text-[#001F3F] mb-3">04. ANALYTICAL RIGOR</h3>
              <p className="text-[14px] leading-[20px]">Leveraging predictive AI to model climate-risk scenarios against five-year revenue projections.</p>
            </div>
          </div>
        </section>

        {/* Section 04: Regulatory Roadmap */}
        <section className="mb-32">
          <div className="bg-white border border-[#c5c6cd] p-8 md:p-12">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-end mb-10 gap-4">
              <div>
                <span className="text-[#7c5800] text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase block mb-2">SECTION 04</span>
                <h2 className="font-serif text-[28px] md:text-[32px] leading-[36px] md:leading-[40px] font-semibold text-[#001F3F]">REGULATORY ROADMAP</h2>
              </div>
              <span className="text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase text-[#4A5568] md:block">UPDATE: Q3 2026 MANDATE</span>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse min-w-[600px]">
                <thead>
                  <tr className="bg-[#001F3F] text-white">
                    <th className="p-4 text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase">PARAMETER</th>
                    <th className="p-4 text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase">BRSR CORE (SEBI)</th>
                    <th className="p-4 text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase">ISSA 5000 (INTL)</th>
                    <th className="p-4 text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase">FORENSIC ALPHA IMPACT</th>
                  </tr>
                </thead>
                <tbody className="text-[14px] leading-[20px] text-[#191c1d]">
                  <tr className="border-b border-[#c5c6cd]">
                    <td className="p-4 font-bold">Assurance Level</td>
                    <td className="p-4 italic">Reasonable Assurance</td>
                    <td className="p-4 italic">Limited/Reasonable</td>
                    <td className="p-4 text-[#7c5800] font-bold">High Scrutiny</td>
                  </tr>
                  <tr className="border-b border-[#c5c6cd]">
                    <td className="p-4 font-bold">Data Provenance</td>
                    <td className="p-4">Internal Systems</td>
                    <td className="p-4">Independent Verify</td>
                    <td className="p-4 text-[#7c5800] font-bold">Valuation Variable</td>
                  </tr>
                  <tr className="border-b border-[#c5c6cd]">
                    <td className="p-4 font-bold">Supply Chain (S3)</td>
                    <td className="p-4">Top 250 Mandate</td>
                    <td className="p-4">Global Holistic</td>
                    <td className="p-4 text-[#7c5800] font-bold">Operational Risk</td>
                  </tr>
                  <tr>
                    <td className="p-4 font-bold">Audit Cycle</td>
                    <td className="p-4">Annual</td>
                    <td className="p-4">Ongoing/Project</td>
                    <td className="p-4 text-[#7c5800] font-bold">Exit Readiness</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </section>

        {/* Section 05: Strategic Mandates */}
        <section className="mb-20">
          <div className="relative bg-[#101c2f] p-8 md:p-12 text-white flex flex-col lg:flex-row items-center justify-between gap-8">
            <div className="lg:w-2/3">
              <span className="text-[#7c5800] text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase block mb-4">SECTION 05</span>
              <h2 className="font-serif text-[28px] md:text-[32px] leading-[36px] md:leading-[40px] font-semibold mb-6">STRATEGIC MANDATES FOR 2026</h2>
              <ul className="space-y-4">
                <li className="flex items-start gap-4">
                  <span className="material-symbols-outlined text-[#7c5800]">check_circle</span>
                  <span className="text-[16px] leading-[24px]">Transition all ESG reporting to a forensic accounting framework by Q1 2026.</span>
                </li>
                <li className="flex items-start gap-4">
                  <span className="material-symbols-outlined text-[#7c5800]">check_circle</span>
                  <span className="text-[16px] leading-[24px]">Implement a "Double Materiality" audit for any asset exceeding ₹1,000 Cr in valuation.</span>
                </li>
                <li className="flex items-start gap-4">
                  <span className="material-symbols-outlined text-[#7c5800]">check_circle</span>
                  <span className="text-[16px] leading-[24px]">Prepare independent assurance dossiers for all cross-border M&A transactions.</span>
                </li>
              </ul>
            </div>
            <div className="lg:w-1/3 flex flex-col gap-4 w-full">
              <button className="bg-[#7c5800] text-white px-8 py-4 text-[12px] leading-[16px] font-bold tracking-[0.05em] uppercase hover:bg-[#5e4200] transition-colors flex items-center justify-center gap-2">
                <span className="material-symbols-outlined">download</span>
                DOWNLOAD PROTOCOL
              </button>
              <p className="text-[14px] leading-[20px] text-[#78849c] text-center italic">Requires Executive Portal Access</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default EsgAsAlpha;
